name: 'Dotnet version tool'
description: 'Greet someone and record the time'
inputs:
  projects: 
    description: 'Projects to set version.
     You can use Glob pattern string (like "**/*.csproj") or Glob patterns array json string (like "["**/*.csproj", ".version", "**/*.version.json"]"). 
     Patterns supported by Globby are supported.Leading ! changes the meaning of an include pattern to exclude.'
    default: "**/*.csproj"
    required: true
  version: 
    description: 'Version to set in semver format'
    required: true
runs:
  using: 'node12'
  main: 'index.js'